name: Feature Tamplate
description: 기능 추가할 때 쓰는 템플릿
title: "[Feature] Title"
labels: ["feature"]

body:
  - type: textarea
    id: feature-contents
    attributes:
      label: feature 설명
      description: feature 설명
      placeholder: e.g. 
    validations:
      required: true
  - type: input
    id: prepare-issue
    attributes:
      label: Prepare Issue(Optional)
      description: 관련된 Prepare가 있다면 적어주세요.
      placeholder: "ex. #14"
    validations:
      required: false
  - type: textarea
    id: related-view
    attributes:
      label: Related View(Optional)
      description: 작업하는 사항에 영향을 받는 View(화면)
      value: |
        - ex. HomeView
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: 우선 순위
      description: Backlog에서의 중요도
      options:
        - ⭐️⭐️⭐️⭐️⭐️
        - ⭐️⭐️⭐️⭐️
        - ⭐️⭐️⭐️
        - ⭐️⭐️
        - ⭐️
    validations:
      required: true
      
  - type: input
    id: expected-period
    attributes:
      label: 예상 소요 기간
      placeholder: ~ MM/dd(E) ex. ~ 07/12(화)
    validations:
      required: true
  - type: input
    id: real-period
    attributes:
      label: 실제 소요 기간
      placeholder: ~ MM/dd(E) ex. ~ 07/12(화)
    validations:
      required: false
